package com.java.activiti.dao;

import com.java.activiti.model.t_leave;
import java.util.List;

public interface t_leaveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_leave
     *
     * @mbggenerated Fri Aug 09 17:30:49 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_leave
     *
     * @mbggenerated Fri Aug 09 17:30:49 CST 2019
     */
    int insert(t_leave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_leave
     *
     * @mbggenerated Fri Aug 09 17:30:49 CST 2019
     */
    t_leave selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_leave
     *
     * @mbggenerated Fri Aug 09 17:30:49 CST 2019
     */
    List<t_leave> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_leave
     *
     * @mbggenerated Fri Aug 09 17:30:49 CST 2019
     */
    int updateByPrimaryKey(t_leave record);
}